controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
update_notification:
    path: /update-notification/{id}
    controller: App\Controller\ProfilController::updateNotificationStatus
    methods: [GET]